codecov:
  require_ci_to_pass: true # Should Codecov wait for all other statues to pass before sending it's status.

coverage:
  precision: 2
  round: down
  range: "75...100"  # The value range where you want the value to be green

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches:               # branch names that can post comment
    - "master"